apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-todoapp
  namespace: mateapp
spec:
  selector:
    matchLabels:
      app: daemonset-todoapp
  template:
    metadata:
      labels:
        app: daemonset-todoapp
    spec:
      containers:
        - name: busyboxplus
          image: busyboxplus:curl
          resources:
            requests:
              memory: "100Mi"
              cpu: "0.1"
            limits:
              memory: "200Mi"
              cpu: "0.2"
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                curl http://todoapp-service.todoapp.svc.cluster.local
                sleep 5
              done
