apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-todoapp
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: busyboxplus
              image: busyboxplus:curl
              resources:
                requests:
                  memory: "100Mi"
                  cpu: "0.1"
                limits:
                  memory: "200Mi"
                  cpu: "0.2"
              command: ["/bin/sh", "-c"]
              args:
                - |
                  curl http://todoapp-service.todoapp.svc.cluster.local/api/health
          restartPolicy: OnFailure